# Generated by Django 3.0.6 on 2020-07-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empty', max_length=200)),
                ('description', models.TextField(default=' ', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=None)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tquestion',
            fields=[
                ('no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(default=' ', max_length=1000)),
                ('A', models.CharField(default=' ', max_length=500)),
                ('B', models.CharField(default=' ', max_length=500)),
                ('C', models.CharField(default=' ', max_length=500)),
                ('D', models.CharField(default=' ', max_length=500)),
                ('answer', models.CharField(default=' ', max_length=500)),
                ('that_Quiz', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Quiz.CustomizeQuiz')),
            ],
        ),
        migrations.CreateModel(
            name='Myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=100)),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('urlhash', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('me', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
