# Generated by Django 3.0.6 on 2020-08-04 05:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20200802_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_or_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_or_branch_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
